# fly.toml app configuration file generated for clock-tracker on 2024-02-03T17:52:26-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'clock-tracker'
primary_region = 'den'

[build]

[env]
  PORT = '8043'

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
